---
title: "PCA"
output: pdf_document
date: '2022-06-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Detection Limit Data}
#Contams with 0.01 dection limit
contams1 <- c("Cl.mg.L", "SO4.mg.L", "Br.mg.L", "NO3.N.mg.L", "Na.mg.L", "K.mg.L", "Mg.mg.L", "Ca.mg.L", "NH4.N.mg.L", "PO4.P", "DOC.mg.L", "TDN.mg.L")
#replace all E. Coli with half of 10 detection limit.
#List with contams only measured in one or part of samplings, also .01 limit
contams2 <- c("E.Coli.CFU.per.100mL")
```


```{r Set up and Clean Data}
#Clear the environment

#Load all libraries
library(devtools)
library(ggfortify) #package that has the functions for PCA
library(tidyverse)
library(knitr)
library(openxlsx)
library(reshape2)
library(cluster)

#Load Data
bc_data3 <- read.csv("SS1-SS2-SS3_MERGED_DATA.csv")
#Remove Duplicate from Data Set
bc_data3 <- bc_data3[!duplicated(bc_data$DOC..mg.L.), ]

#change september 2022 to 2021

bc_data3[35:64, "DATE"] <- "2021-09-25"


#Fill in NA values with half of the detection limit
#df %>% mutate_at(vars(c("AAA", "BAA":"BBA", "BBB")), ~replace_na(.,0))
bc_dataRepNA <- bc_data3 %>% mutate_at(vars(contams1), ~replace_na(., .005))
#bc_data <- bc_data %>% mutate_at(vars("E.Coli..CFU.per.100mL."), ~replace_na(5))

#remove column at bottom with NAs
bc_dataRepNA <- bc_dataRepNA[-(99),]

#filter to only columns with non-NA values and relevant params
  #check which columns have NA
colSums(is.na(jonnyData))


extraCols <- jonnyData[, c(2,25, 28, 30,36, 40)]

bc_dataRepNA <- left_join(bc_dataRepNA, extraCols)
bc_dataRepNA <- bc_dataRepNA[!duplicated(bc_dataRepNA$X), ]

#list of color params for PCA

```



```{r Conduct PCA}
#subset of just September and Feb. samples
pca1 <- prcomp(bc_dataRepNA[, c(4:15)], center = TRUE, scale=TRUE)

summary(pca1)
```

```{r PCA plots}
#code for removing NAs for developed

plota <- autoplot(pca1, x=1, y=2, data=bc_dataRepNA, colour = 'roadDensity_kmkm2',  
          main = "PCA of Ellerbe Creek September, February, June Surveys",
         alpha=0.7, loadings.colour='black', loadings.label.colour='black',
         loadings=TRUE, loadings.label=TRUE, size=3) + scale_fill_continuous(limits = c(60, 100))
theme_classic()

plota
plotb <- autoplot(pca1, x=1, y=2, data=bc_dataRepNA, colour = 'DATE',  
                  frame = TRUE, 
          main = "PCA of Ellerbe Creek September, February, June Surveys",
         alpha=0.7, loadings.colour='black', loadings.label.colour='black',
         loadings=TRUE, loadings.label=TRUE, size=3) + theme_classic()

plotb
#rddensity, medianHHIncome, pipedensity, impervious, remove NAs
```

PCA with Durham Data and eight sites in Ellebe Creek

```{r fix Durham Data}
#shrink data set to contain only Station name, date, Param, Value
wider_durham <- active_sitesReal[, c(2, 4:6)]

#removed duplicates by taking avg of lists(lists contain uniform values)
wider_durham <- wider_durham %>% pivot_wider(id_cols = c("Date.Time", "Station.Name"), names_from = "Parameter", values_from = "Value", values_fn = list("Value" = mean))


#remove copper col
wider_select <- wider_durham

#count # of NAs per col
colSums(is.na(wider_durham))

#select params wanting to use for PCA
wider_select <- wider_select[, c(1:2, 6, 10, 12, 14:16, 18, 20, 21, 23)]

wider_select_2 <- wider_durham[, c(4, 7, 14, 20:21, 33, 37:39)]
#eliminate all null values
wider_select <- na.omit(wider_select)

#write for loop to do elim all null values for each param.
#wider_select <- wider_select[ !grepl("NULL", wider_select$), ] 
```

```{r PCA analysis Durham Data}
wider_select <- wider_select[which(wider_select$Station.Name %in% c("EL8.5SEC", "EL5.5GC")),]
pca2 <- prcomp(wider_select[, c(3:11)], center = TRUE, scale=TRUE) 
summary(pca2)
```

```{r PCA Plot Durham Data}
plotc <-autoplot(pca2, x=1, y=2, data= wider_select, colour = 'Station.Name', main = "PCA of Ellerbe Creek Sampling Sites Durham Data", frame = TRUE,
                 #could take off arrows option
         alpha=0.7, loadings.colour='black', loadings.label.colour='black',
         loadings=TRUE, loadings.label=TRUE, size=3) + theme_classic()
plotc
```


